### PR TITLE
[Module Store UI] Add total number in paranthesis

### PR DESCRIPTION
**Pull request by FjorgeTheHuman**
That's where the total amount of modules in the category will go, but I can't figure out how to get that number. Pls help goose

### CODE REVIEW

**Comment by FjorgeTheHuman** [comment]
Oh also, I think this is a nice feature because it's handy to be able to see the total modules in a category or by an author without selecting them in the module store

**Comment by CanadaHonk** [comment]
Adding total is not really needed and I feel it would just overwhelm the user with the amount of different numbers.

**Comment by FjorgeTheHuman** [comment]
I don't think anyone would be overwhelmed by an extra number, but I can see how it's unneeded

**Comment by CanadaHonk** [comment]
I mean it's because an extra number next to every single selector.

**Comment by CanadaHonk** [comment]
Closing due to inactivity / unwanted mostly.

**Pull request closed without merging**
